export const SUPABASE_URL = "https://magghzdzdbllkmnjegwr.supabase.co"

export const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZ2doemR6ZGJsbGttbmplZ3dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTE1Njg3MzAsImV4cCI6MjAwNzE0NDczMH0.9K7UOWZ2iL_kL3bXfaoSD_61-Y2voFKqTONiebZAnmI"